 # Find the sample which could be treated with the greates number of drugs

SELECT SAMPLE, MAX(NUM_SAMPLE) AS MAX_DRUG
FROM (
SELECT COUNT(RNA.SAMPLE) AS NUM_SAMPLE,RNA.SAMPLE
FROM RNA AS RNA JOIN THRESHOLDS AS TH ON RNA.GENE = TH.GENE
WHERE RNA.FPKM>TH.THSD
AND EXISTS ( 
	SELECT ENSEMBLGENEID
	FROM CONVERTER
	WHERE HUGO_GENE IN (
		SELECT HUGO_GENE
		FROM oncokb_drug))
		GROUP BY RNA.SAMPLE) AS MAX_SAMPLE;