# Find tumor suppressor genes that are overexpressed in at least 8 types of cancer

SELECT COUNT(DISTINCT RNA.CANCER) AS NUM_CANCER, RNA.GENE
FROM RNA AS RNA JOIN THRESHOLDS AS TH ON RNA.GENE=TH.GENE
WHERE RNA.FPKM>TH.THSD 
AND RNA.GENE IN (
	SELECT ENSEMBLGENEID
	FROM CONVERTER
	WHERE EXISTS (
		SELECT HUGO_GENE 
		FROM ONCO_GENES 
		WHERE ISTUMORSUPPRESSORGENE = 'YES') AND ENSEMBLGENEID IS NOT NULL)
GROUP BY RNA.GENE
HAVING NUM_CANCER > 8
ORDER BY NUM_CANCER DESC;