# Find those genes (or the gene) that do not pass threshold even if they are annotated in oncokb

SELECT DISTINCT RNA.GENE
FROM RNA AS RNA JOIN THRESHOLDS AS TH ON RNA.GENE=TH.GENE 
WHERE RNA.FPKM<TH.THSD 
AND (RNA.GENE) IN (
SELECT EnsemblgeneID 
FROM CONVERTER 
WHERE (HUGO_GENE) IN (
SELECT HUGO_GENE FROM ONCO_GENES WHERE ISONCOGENE = 'YES'));

